IP: 192.168.3.200
DATASOURCE_URL: ${IP}:5432
DATASOURCE_USERNAME: postgres
DATASOURCE_PASSWORD: 123456
KAFKA_BOOTSTRAP_SERVERS: ${IP}:9092
REDIS_URL: ${IP}:6379
PGSQLSSLROOT: C:/Users/yanglei/Documents/pgsqlssl
feign:
  client:
    config:
      default:
        loggerLevel: full
logging:
  level:
    root: info
    com:
      kyyee: debug
server:
  port: 52000
spring:
  redis:
    database: 0
kyyee:
  log:
    url: http://${IP}:11102
  service:
    bss-gateway: http://${IP}:11125
    bss-uuv: http://${IP}:11101
    imss-vx: http://${IP}:9095
    mg-fms82upLoad: http://${IP}:14178
    mg-fms85: http://${IP}:14177
    mg-om: http://${IP}:14548
    uss-base: http://${IP}:16504
    viid-mda: http://${IP}:2530

  file:
    save-dir: D:/home/file/
